//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmniWatch.Integrations.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Integrations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Integrations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OmniWatch.Integrations.Resources.Integrations", typeof(Integrations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load forecast for city {0}..
        /// </summary>
        internal static string Ipma_LoadForecastCityFailed {
            get {
                return ResourceManager.GetString("Ipma_LoadForecastCityFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load forecast for day {0}..
        /// </summary>
        internal static string Ipma_LoadForecastDayFailed {
            get {
                return ResourceManager.GetString("Ipma_LoadForecastDayFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load locations..
        /// </summary>
        internal static string Ipma_LoadLocationsFailed {
            get {
                return ResourceManager.GetString("Ipma_LoadLocationsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load precipitation data..
        /// </summary>
        internal static string Ipma_LoadPrecipitationFailed {
            get {
                return ResourceManager.GetString("Ipma_LoadPrecipitationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load seismic data for area {0}..
        /// </summary>
        internal static string Ipma_LoadSeismicFailed {
            get {
                return ResourceManager.GetString("Ipma_LoadSeismicFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load warnings..
        /// </summary>
        internal static string Ipma_LoadWarningsFailed {
            get {
                return ResourceManager.GetString("Ipma_LoadWarningsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load weather types..
        /// </summary>
        internal static string Ipma_LoadWeatherTypesFailed {
            get {
                return ResourceManager.GetString("Ipma_LoadWeatherTypesFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load wind speed data..
        /// </summary>
        internal static string Ipma_LoadWindFailed {
            get {
                return ResourceManager.GetString("Ipma_LoadWindFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache cleared successfully..
        /// </summary>
        internal static string Noaa_CacheCleared {
            get {
                return ResourceManager.GetString("Noaa_CacheCleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache cleared successfully. The app will download new data..
        /// </summary>
        internal static string Noaa_CacheClearedDownload {
            get {
                return ResourceManager.GetString("Noaa_CacheClearedDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleaning the database....
        /// </summary>
        internal static string Noaa_CleaningDatabase {
            get {
                return ResourceManager.GetString("Noaa_CleaningDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to clear cache..
        /// </summary>
        internal static string Noaa_ClearCacheFailed {
            get {
                return ResourceManager.GetString("Noaa_ClearCacheFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBTrACS out of date. Clearing all historical tables..
        /// </summary>
        internal static string Noaa_IbtracsClearing {
            get {
                return ResourceManager.GetString("Noaa_IbtracsClearing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dataset IBTrACS updated on server. Refreshing global cache....
        /// </summary>
        internal static string Noaa_IbtracsUpdated {
            get {
                return ResourceManager.GetString("Noaa_IbtracsUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid 0,0 coordinate skipped for storm {0}.
        /// </summary>
        internal static string Noaa_InvalidCoordinates {
            get {
                return ResourceManager.GetString("Noaa_InvalidCoordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading active NOAA storms..
        /// </summary>
        internal static string Noaa_LoadActiveStormsError {
            get {
                return ResourceManager.GetString("Noaa_LoadActiveStormsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load active storms from NOAA..
        /// </summary>
        internal static string Noaa_LoadActiveStormsFailed {
            get {
                return ResourceManager.GetString("Noaa_LoadActiveStormsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual cache clear requested by user..
        /// </summary>
        internal static string Noaa_ManualClearRequested {
            get {
                return ResourceManager.GetString("Noaa_ManualClearRequested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving records... ({0} points processed).
        /// </summary>
        internal static string Noaa_SavingRecords {
            get {
                return ResourceManager.GetString("Noaa_SavingRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching for {0} data in local database....
        /// </summary>
        internal static string Noaa_SearchingYear {
            get {
                return ResourceManager.GetString("Noaa_SearchingYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction failed while refreshing cache..
        /// </summary>
        internal static string Noaa_TransactionFailed {
            get {
                return ResourceManager.GetString("Noaa_TransactionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data for {0} not found. Processing from NOAA remote server....
        /// </summary>
        internal static string Noaa_YearNotFound {
            get {
                return ResourceManager.GetString("Noaa_YearNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year synchronization completed..
        /// </summary>
        internal static string Noaa_YearSyncCompleted {
            get {
                return ResourceManager.GetString("Noaa_YearSyncCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load flights from OpenSky.
        /// </summary>
        internal static string OpenSky_FailedToLoad_Flights {
            get {
                return ResourceManager.GetString("OpenSky_FailedToLoad_Flights", resourceCulture);
            }
        }
    }
}
